words = [
    "boostrap",
    "chrono",
    "defmt",
    "eabihf",
    "exti",
    "linker's",
    "mcu",
    "moder",
    "nmagic",
    "pwm",
    "pwm's",
    "semihosting",
    "stm",
    "tdefmt",
    "thumbv",
    "tlink",
    "uptime",
]
