words = [
    "boostrap",
    "chrono",
    "clk",
    "debouncer",
    "defmt",
    "dma",
    "dyn",
    "eabihf",
    "exti",
    "gpdma",
    "ish",
    "linker's",
    "mcu",
    "microcontroller",
    "mille",
    "mipidsi",
    "moder",
    "mosi",
    "mpu",
    "nmagic",
    "pwm",
    "pwm's",
    "semihosting",
    "stm",
    "tdefmt",
    "thumbv",
    "tlink",
    "uptime",
    "vcc",
    "xout",
]
